
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import java.util.Arrays;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    List<String> digs = new ArrayList<String>(Arrays.asList(new String[]{"1", "2", "3", "4", "5"}));
    List<String> arrToCampare = new ArrayList<String>(Arrays.asList(new String[]{"1", "3", "5"}));

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }

    void run() {
//        printList(removeSeconds1(this.digs), "removeSeconds1");

        printList(arrToCampare, "should be");
        printList(removeSeconds2(this.digs), "removeSeconds2");
        printList(removeSeconds3(this.digs), "removeSeconds3");
        printList(removeSeconds4(this.digs), "removeSeconds4");
    }

    // 1
    public List<String> removeSeconds1(List<String> digs) {
        for (String i : digs) {
//            digs.remove(i);
        }
        return digs;
    }

    // 2
    public List<String> removeSeconds2(List<String> digs) {
        for (int i = 0; i <= digs.size(); i++) {
            if (i % 2 == 0)
                digs.remove(i);
        }
        return digs;
    }

    // 3
    public List<String> removeSeconds3(List<String> digs) {
        boolean second = false;
        for (Iterator<String> it = digs.iterator(); it.hasNext(); ) {
            it.next();
            if (second)
                it.remove();
            second = !second;
        }
        return digs;
    }

    // 4
    public List<String> removeSeconds4(List<String> digs) {
        Iterator<String> it = digs.iterator();
        int i = 0;
        while (it.hasNext()) {
            it.next();
            if (i % 2 == 0) {
                it.remove();
            }
            i++;
        }
        return digs;
    }

    // Utils
    void printList(List<String> list, String arrayName) {
        System.out.print(arrayName + ": ");
        for (String item : list) {
            System.out.print(item + ", ");
        }
        System.out.println();
    }

}
