/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Before;
import org.junit.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;

public class AppTest {
//    App app = new App();

    List<String> digs = new ArrayList<String>(Arrays.asList(new String[]{"1", "2", "3", "4", "5"}));
    List<String> arrToCampare = new ArrayList<String>(Arrays.asList(new String[]{"1", "3", "5"}));

//    @Before void init() {
//        this.app = new App();
//    }

    @Test public void removeSeconds1Test() {
        App app = new App();
        assertEquals(app.removeSeconds1(this.digs), is(this.arrToCampare));
    }

    @Test public void removeSeconds2Test() {
        App app = new App();
        assertEquals(app.removeSeconds2(this.digs), is(this.arrToCampare));
    }

    @Test public void removeSeconds3Test() {
        App app = new App();
        assertEquals(app.removeSeconds3(this.digs), is(this.arrToCampare));
    }



}
